# Generated by Django 5.2.5 on 2025-09-03 14:08

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0002_datacontract_id_alter_datacontract_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("REST", "Rest"), ("WMS", "Wms"), ("WFS", "Wfs")],
                        help_text="Soort API: REST, atom, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="API Type",
                    ),
                ),
                ("endpoint_url", models.URLField(verbose_name="API Link (Intern)")),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, verbose_name="Description"),
                ),
                (
                    "acronym",
                    models.CharField(max_length=10, unique=True, verbose_name="Acronym"),
                ),
                (
                    "po_name",
                    models.CharField(max_length=64, verbose_name="Product Owner Name"),
                ),
                (
                    "po_email",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.EmailValidator],  # ty: ignore
                        verbose_name="Product Owner Email",
                    ),
                ),
                (
                    "contact_email",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.EmailValidator],  # ty: ignore
                        verbose_name="Contact E-mail",
                    ),
                ),
                (
                    "scope",
                    models.CharField(max_length=64, verbose_name="Scope (Entra Group)"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="datateam",
        ),
        migrations.RemoveField(
            model_name="filedistribution",
            name="distribution",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="_owner",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="crs",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="distribution",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="is_geo",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="language",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="privacy",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="refresh_period",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="schema",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="schema_url",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="themes",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="version",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="table",
        ),
        migrations.AddField(
            model_name="datacontract",
            name="conditions",
            field=models.TextField(
                blank=True,
                help_text="De voorwaarden van het datacontract",
                null=True,
                verbose_name="Voorwaarden",
            ),
        ),
        migrations.AddField(
            model_name="datacontract",
            name="has_personal_data",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Bevat Persoonsgegevens"
            ),
        ),
        migrations.AddField(
            model_name="datacontract",
            name="has_special_personal_data",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Bevat Bijzondere Persoonsgegevens",
            ),
        ),
        migrations.AddField(
            model_name="datacontract",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="datacontract",
            name="profile",
            field=models.URLField(
                blank=True,
                help_text="Verwijzing naar een profiel beschreven in Amsterdam Schema.",
                null=True,
                verbose_name="Amsterdam Schema Profiel verwijzing (url)",
            ),
        ),
        migrations.AddField(
            model_name="datacontract",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Draft"),
                    ("R", "In review"),
                    ("A", "Approved"),
                    ("P", "Published"),
                    ("E", "Expired"),
                ],
                max_length=1,
                null=True,
                verbose_name="Publicatiestatus",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="access_url",
            field=models.URLField(
                blank=True,
                help_text="Toegangslink naar de distributie.",
                null=True,
                verbose_name="Access URL",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="contract",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="beheeromgeving.datacontract",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distribution",
            name="download_url",
            field=models.URLField(
                blank=True,
                help_text="Link naar het bestand dat opgeslagen is binnen de omgeving van het Datateam op het Dataplatform",
                null=True,
                verbose_name="Download URL",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="format",
            field=models.CharField(
                blank=True,
                help_text="Het bestandsformaat: CSV, CAD, etc.",
                max_length=10,
                null=True,
                verbose_name="Bestandstype",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="refresh_period",
            field=models.CharField(
                blank=True,
                help_text="Om de hoeveel tijd de data in het Data Product ververst wordt",
                max_length=64,
                null=True,
                verbose_name="Ververstermijn",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="type",
            field=models.CharField(
                choices=[
                    ("D", "Dashboard"),
                    ("M", "Folder"),
                    ("F", "File"),
                    ("C", "Custom"),
                    ("A", "Api"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="confidentiality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O", "Openbaar"),
                    ("I", "Intern"),
                    ("V", "Vertrouwelijk"),
                    ("G", "Geheim"),
                ],
                help_text="Het niveau van vertrouwelijkheid van de data in het Data Contract. Vereiste voor BBN",
                null=True,
                verbose_name="Vertrouwelijkheidsniveau",
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="data_steward",
            field=models.CharField(
                blank=True,
                help_text="Contact E-mail adres van de verantwoordelijke Data Steward in de business",
                null=True,
                validators=[django.core.validators.EmailValidator],  # ty: ignore
                verbose_name="Business Data Steward",
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Beschrijving en betekenis van het Data Contract",
                null=True,
                verbose_name="Beschrijving",
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="De naam van het Data Contract. Deze moet uniek zijn",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Naam",
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="purpose",
            field=models.TextField(
                blank=True,
                help_text="Beschrijf hier de doelbinding aan de hand van de use-case(s) waarvoor dit Data Contract is bedoeld en zijn bestaansrecht aan ontleent. Het uitgangspunt van doelbinding is, dat gegevens worden verwerkt en verzameld voor een welbepaald, uitdrukkelijk omschreven en gerechtvaardigde doel. 'Welbepaald en uitdrukkelijk omschreven' houdt in dat men geen gegevens mag verzamelen zonder een precieze doelomschrijving",
                null=True,
                verbose_name="Doelbinding",
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="retainment_period",
            field=models.IntegerField(
                blank=True,
                help_text="Om te voldoen aan de duurzame toegankelijkheidseisen (DUTO) van de overheid is het nodig om een bewaartermijn vast te leggen voor Data Producten zodat het Datateam hun omgeving hierop kan inrichten en de data te verwijderen wanneer dat nodig is",
                null=True,
                verbose_name="Bewaartermijn in maanden",
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Datum waarop het Datacontract ingaat, en dus actief wordt. Deze datum kan in de toekomst liggen en kan een andere datum zijn dan de aanmaak datum van het Data Product. Dit is van belang wanneer er een nieuwe versie van het datacontract wordt gemaakt. Dit is geen systeemveld (zoals Aanmaak -en Wijzigingsdatum) en moet daarom separaat worden opgegeven. Wanneer het de innitiele versie van het Data Product betreft, vul hier dan de aanmaakdatum van het contract in. Wanneer het Data Product gemigreerd is vanaf de oude Data Catalogus, vul hier dan de publicatiedatum van de oude catalogus (Issued) in.",
                null=True,
                verbose_name="Startdatum Contract",
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="access_service",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribution",
                to="beheeromgeving.dataservice",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="De naam van het Product. Deze moet uniek zijn",
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Naam",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Beschrijving en betekenis van het Data Product",
                        null=True,
                        verbose_name="Beschrijving",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("D", "Dataproduct"), ("I", "Informatieproduct")],
                        max_length=1,
                        null=True,
                        verbose_name="Product type",
                    ),
                ),
                (
                    "themes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("B", "Bestuur"),
                                ("CR", "Cultuur en recreatie"),
                                ("E", "Economie"),
                                ("F", "Financien"),
                                ("H", "Huisvesting"),
                                ("I", "Internationaal"),
                                ("L", "Landbouw"),
                                ("MI", "Migratie en integratie"),
                                ("NM", "Natuur en milieu"),
                                ("OW", "Onderwijs en wetenschap"),
                                ("OOV", "Openbare orde en veiligheid"),
                                ("R", "Recht"),
                                ("RI", "Ruimte en infrastructuur"),
                                ("SZ", "Sociale zekerheid"),
                                ("V", "Verkeer"),
                                ("W", "Werk"),
                                ("ZG", "Zorg en gezondheid"),
                            ],
                            max_length=32,
                            verbose_name="Thema('s)",
                        ),
                        blank=True,
                        help_text="Thema's voor Data Producten zoals gedefinieerd als de thema's op nationaal niveau. Dit geeft de mogelijkheid om te koppelen op de nationale repository.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32, verbose_name="Zoekwoorden"),
                        blank=True,
                        help_text="Zoekwoorden of Tags die het Data Product of zijn inhoud beschrijven. Dit is bedoeld om de vindbaarheid in de Data Catalogus te ondersteunen. Het gaat om een logische groepering van Data Producten.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "_owner",
                    models.CharField(
                        blank=True,
                        help_text="De eigenaar van het Data Product. Standaard is dit de Product Owner van het betreffende Datateam, tenzij anders overeengekomen. Pas in dat geval de waarde aan",
                        max_length=64,
                        null=True,
                        verbose_name="Eigenaar",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "Draft"),
                            ("R", "In review"),
                            ("A", "Approved"),
                            ("P", "Published"),
                            ("E", "Expired"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Publicatiestatus",
                    ),
                ),
                (
                    "refresh_period",
                    models.CharField(
                        blank=True,
                        help_text="Om de hoeveel tijd de data in het Data Product ververst wordt",
                        max_length=64,
                        null=True,
                        verbose_name="Ververstermijn",
                    ),
                ),
                (
                    "has_personal_data",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Bevat Persoonsgegevens"
                    ),
                ),
                (
                    "has_special_personal_data",
                    models.BooleanField(
                        default=False,
                        null=True,
                        verbose_name="Bevat Bijzondere Persoonsgegevens",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("NL", "Nederlands"), ("EN", "English")],
                        help_text="De gebruikte taal in de inhoud van het Data Product",
                        null=True,
                        verbose_name="Taal",
                    ),
                ),
                (
                    "schema_url",
                    models.URLField(
                        blank=True,
                        help_text="Verwijzing naar een dataset beschreven in Amsterdam Schema. Dit is alleen een vervanging voor het schema, niet de rest van het Data Contract. Als het 'Schema' veld is ingevuld en je geen gebruik maakt van Amsterdam Schema, dan blijft dit veld leeg",
                        null=True,
                        verbose_name="Amsterdam Schema Dataproduct verwijzing (url)",
                    ),
                ),
                (
                    "is_geo",
                    models.BooleanField(
                        blank=True,
                        help_text="Of het Data Product al dan niet geografische data bevat",
                        null=True,
                        verbose_name="Geo Data",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(related_name="sinks", to="beheeromgeving.product"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Het team verantwoordelijk voor en gekoppeld aan het Data Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="beheeromgeving.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataservice",
            name="product",
            field=models.ForeignKey(
                help_text="Het Product waar deze service bij hoort",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="beheeromgeving.product",
            ),
        ),
        migrations.AddField(
            model_name="datacontract",
            name="product",
            field=models.ForeignKey(
                default=None,
                help_text="Het Product waar dit contract bij hoort",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="beheeromgeving.product",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="APIDistribution",
        ),
        migrations.DeleteModel(
            name="DataTeam",
        ),
        migrations.DeleteModel(
            name="FileDistribution",
        ),
    ]
