# Generated by Django 5.2.5 on 2025-09-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0003_dataservice_team_remove_datacontract_datateam_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacontract",
            name="conditions",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.AddField(
            model_name="datacontract",
            name="scope",
            field=models.URLField(
                blank=True,
                help_text="Verwijzing naar een scope beschreven in Amsterdam Schema.",
                null=True,
                verbose_name="Amsterdam Schema scope verwijzing (url)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="crs",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RD", "RD"),
                    ("ETRS89", "ETRS89"),
                    ("WGS84", "WGS84"),
                    ("UTM35S", "UTM35S"),
                ],
                help_text="Geo-informatie is direct gekoppeld aan een locatie op aarde. De manier waarop die koppeling wordt gelegd, wordt beschreven in het coördinaatreferentiesysteem (CRS). Hierin worden coördinaten van een locatie vastgelegd",
                null=True,
                verbose_name="Geo coördinaatreferentiesysteem",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="refresh_period",
            field=models.JSONField(
                default=dict,
                help_text='De ververstermijn in de vorm {"frequency": int, "unit": periodString}, waarbij periodStr iets is als "uur", "dag", "week", "maand", "jaar"',
                null=True,
                verbose_name="Ververstermijn",
            ),
        ),
    ]
