# Generated by Django 5.2.5 on 2025-09-23 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beheeromgeving", "0004_remove_datacontract_conditions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacontract",
            name="data_steward",
        ),
        migrations.AddField(
            model_name="product",
            name="_contact_email",
            field=models.CharField(
                blank=True,
                help_text="Contact E-mail adres van het team",
                max_length=128,
                null=True,
                validators=[django.core.validators.EmailValidator],
                verbose_name="Contact Email",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="data_steward",
            field=models.CharField(
                blank=True,
                help_text="Contact E-mail adres van de verantwoordelijke Data Steward in de business",
                null=True,
                validators=[django.core.validators.EmailValidator],
                verbose_name="Business Data Steward",
            ),
        ),
    ]
