# Generated by Django 5.2.5 on 2025-09-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0005_remove_datacontract_data_steward_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataservice",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REST", "Rest"),
                    ("WMS", "Wms"),
                    ("WFS", "Wfs"),
                    ("MVT", "Mvt"),
                    ("ATOM", "Atom"),
                ],
                help_text="Soort API: REST, atom, etc.",
                max_length=10,
                null=True,
                verbose_name="API Type",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=128, unique=True, verbose_name="Name"),
        ),
    ]
