# Generated by Django 5.2.6 on 2025-10-09 11:28

from django.db import migrations, models


def forward(apps, schema_editor):
    Product = apps.get_model("beheeromgeving", "Product")
    DataContract = apps.get_model("beheeromgeving", "DataContract")
    for product in Product.objects.all():
        if product.has_special_personal_data:
            product.privacy_level = "BI"
        elif product.has_personal_data:
            product.privacy_level = "PI"
        else:
            product.privacy_level = "NPI"
        product.save()

    for contract in DataContract.objects.all():
        if contract.has_special_personal_data:
            contract.privacy_level = "BI"
        elif contract.has_personal_data:
            contract.privacy_level = "PI"
        else:
            contract.privacy_level = "NPI"
        contract.save()


def backward(apps, schema_editor):
    Product = apps.get_model("beheeromgeving", "Product")
    DataContract = apps.get_model("beheeromgeving", "DataContract")
    for product in Product.objects.all():
        if product.privacy_level == "BI":
            product.has_special_personal_data = True
            product.has_personal_data = True
        if product.privacy_level == "PI":
            product.has_personal_data = True
            product.has_special_personal_data = False
        else:
            product.has_personal_data = False
            product.has_special_personal_data = False
        product.save()

    for contract in DataContract.objects.all():
        if contract.privacy_level == "BI":
            contract.has_special_personal_data = True
            contract.has_personal_data = True
        if contract.privacy_level == "PI":
            contract.has_personal_data = True
            contract.has_special_personal_data = False
        else:
            contract.has_personal_data = False
            contract.has_special_personal_data = False
        contract.save()


class Migration(migrations.Migration):

    dependencies = [
        ("beheeromgeving", "0006_alter_dataservice_type_alter_team_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacontract",
            name="privacy_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NPI", "Niet persoonlijk identificeerbaar"),
                    ("PI", "Persoonlijk identificeerbaar"),
                    ("BI", "Bijzonder identificeerbaar"),
                ],
                help_text="Het privacyniveau van het contract",
                null=True,
                verbose_name="Privacyniveau",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="privacy_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NPI", "Niet persoonlijk identificeerbaar"),
                    ("PI", "Persoonlijk identificeerbaar"),
                    ("BI", "Bijzonder identificeerbaar"),
                ],
                help_text="Het privacyniveau van het product",
                null=True,
                verbose_name="Privacyniveau",
            ),
        ),
        migrations.RunPython(forward, backward),
        migrations.RemoveField(
            model_name="datacontract",
            name="has_personal_data",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="has_special_personal_data",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_personal_data",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_special_personal_data",
        ),
    ]
