# Generated by Django 5.2.6 on 2025-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beheeromgeving", "0006_alter_dataservice_type_alter_team_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacontract",
            name="has_personal_data",
        ),
        migrations.RemoveField(
            model_name="datacontract",
            name="has_special_personal_data",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_personal_data",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_special_personal_data",
        ),
        migrations.AddField(
            model_name="datacontract",
            name="privacy_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NPI", "Niet persoonlijk identificeerbaar"),
                    ("PI", "Persoonlijk identificeerbaar"),
                    ("BI", "Bijzonder identificeerbaar"),
                ],
                help_text="Het privacyniveau van het contract",
                null=True,
                verbose_name="Privacyniveau",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="privacy_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NPI", "Niet persoonlijk identificeerbaar"),
                    ("PI", "Persoonlijk identificeerbaar"),
                    ("BI", "Bijzonder identificeerbaar"),
                ],
                help_text="Het privacyniveau van het product",
                null=True,
                verbose_name="Privacyniveau",
            ),
        ),
    ]
