# Generated by Django 5.2.7 on 2025-11-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0007_remove_datacontract_has_personal_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataservice",
            name="endpoint_url",
            field=models.URLField(blank=True, null=True, verbose_name="API Link (Intern)"),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Dashboard"),
                    ("M", "Folder"),
                    ("F", "File"),
                    ("C", "Custom"),
                    ("A", "Api"),
                ],
                null=True,
            ),
        ),
    ]
