# Generated by Django 5.2.7 on 2025-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0008_alter_dataservice_endpoint_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="De naam van het bestand.",
                max_length=255,
                null=True,
                verbose_name="Bestandsnaam",
            ),
        ),
    ]
