# Generated by Django 5.2.7 on 2025-12-04 12:54

from django.db import migrations

from beheeromgeving.migration_utils import fix_distribution_format


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0009_distribution_filename"),
    ]

    operations = [migrations.RunPython(fix_distribution_format, migrations.RunPython.noop)]
