# Generated by Django 5.2.7 on 2025-12-04 12:54

from django.db import migrations

SEPARATORS = ["_", " ", ";", ","]


def forward(apps, schema_editor):
    Distribution = apps.get_model("beheeromgeving", "Distribution")
    for distribution in Distribution.objects.all():
        for sep in SEPARATORS:
            if distribution.format is not None and sep in distribution.format:
                distribution.format = distribution.format.split(sep)[0]
                distribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ("beheeromgeving", "0009_distribution_filename"),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
