# Generated by Django 5.2.7 on 2025-12-16 14:28

from django.db import migrations

from beheeromgeving.migration_utils import revert_team_scopes, update_team_scopes


class Migration(migrations.Migration):

    dependencies = [
        ("beheeromgeving", "0011_datacontract_created_at_product_created_at"),
    ]

    operations = [migrations.RunPython(update_team_scopes, reverse_code=revert_team_scopes)]
