# Generated by Django 5.2.7 on 2025-12-29 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0012_update_team_scopes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="privacy_level",
        ),
    ]
