# Generated by Django 5.2.7 on 2025-12-30 10:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0013_remove_product_privacy_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacontract",
            name="tables",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64, verbose_name="Tabellen"),
                blank=True,
                help_text="De ids van de tabellen binnen de dataset die onder dit contract vallen. Laat leeg om alle tabellen op te nemen.",
                null=True,
                size=None,
            ),
        ),
    ]
