# Generated by Django 5.2.10 on 2026-01-26 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0014_datacontract_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="_contact_email",
            field=models.CharField(
                blank=True,
                help_text="Contact E-mail adres van het team",
                max_length=128,
                null=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Contact Email",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="data_steward",
            field=models.CharField(
                blank=True,
                help_text="Contact E-mail adres van de verantwoordelijke Data Steward in de business",
                null=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Business Data Steward",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="contact_email",
            field=models.CharField(
                max_length=64,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Contact E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="po_email",
            field=models.CharField(
                max_length=64,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Product Owner Email",
            ),
        ),
    ]
