# Generated by Django 5.2.11 on 2026-02-19 10:09

import django.contrib.postgres.fields
from django.db import migrations, models

from beheeromgeving.migration_utils import transfer_scopes_backward, transfer_scopes_forward


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0015_alter_product__contact_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datacontract",
            old_name="scope",
            new_name="_scope",
        ),
        migrations.AddField(
            model_name="datacontract",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64, verbose_name="Scopes"),
                blank=True,
                help_text="De scope ids die gebruiken moet hebben om dit contract te kunnen afnemen.",
                null=True,
                size=None,
            ),
        ),
        migrations.RunPython(transfer_scopes_forward, reverse_code=transfer_scopes_backward),
        migrations.RemoveField(
            model_name="datacontract",
            name="_scope",
        ),
    ]
