# Generated by Django 5.2.12 on 2026-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0016_contract_allows_multiple_scopes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataservice",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REST", "Rest"),
                    ("WMS", "Wms"),
                    ("WMTS", "Wmts"),
                    ("WFS", "Wfs"),
                    ("MVT", "Mvt"),
                    ("ATOM", "Atom"),
                ],
                help_text="Soort API: REST, atom, etc.",
                max_length=10,
                null=True,
                verbose_name="API Type",
            ),
        ),
    ]
