# Generated by Django 5.2.12 on 2026-03-16 13:08

from django.db import migrations

from beheeromgeving.migration_utils import set_po_name


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0017_alter_dataservice_type"),
    ]

    operations = [migrations.RunPython(set_po_name, migrations.RunPython.noop)]
