# Generated by Django 5.2.12 on 2026-03-16 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0018_anonymize_po_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="crs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("RD", "RD"),
                        ("ETRS89", "ETRS89"),
                        ("WGS84", "WGS84"),
                        ("UTM35S", "UTM35S"),
                    ],
                    verbose_name="Geo coördinaatreferentiesysteem",
                ),
                blank=True,
                help_text="Geo-informatie is direct gekoppeld aan een locatie op aarde. De manier waarop die koppeling wordt gelegd, wordt beschreven in het coördinaatreferentiesysteem (CRS). Hierin worden coördinaten van een locatie vastgelegd. Een distributie kan meerdere CRS'en ondersteunen.",
                null=True,
                size=None,
            ),
        ),
    ]
