# Generated by Django 5.2.12 on 2026-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0019_distribution_crs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPublishedSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Most recently published content for the public catalogue; " # Please translate this
                        "edits are in this row until republished.", # Please translate this
                        null=True,
                        verbose_name="Gepubliceerde snapshot",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Time of last snapshot publication",# Please translate this
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="published_snapshot_record",
                        to="beheeromgeving.product",
                    ),
                ),
            ],
        ),
    ]
