# Generated by Django 5.2.12 on 2026-04-08 08:56

from django.db import migrations, models

from beheeromgeving.migration_utils import set_publication_dates


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0019_distribution_crs"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacontract",
            name="publication_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Datum waarop het Data Contract voor het eerst is gepubliceerd.",
                null=True,
                verbose_name="Publicatiedatum",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="publication_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Datum waarop het Data Product voor het eerst is gepubliceerd.",
                null=True,
                verbose_name="Publicatiedatum",
            ),
        ),
        migrations.AlterField(
            model_name="datacontract",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Draft"),
                    ("R", "In review"),
                    ("A", "Approved"),
                    ("P", "Published"),
                    ("E", "Expired"),
                    ("X", "Deleted"),
                ],
                max_length=1,
                null=True,
                verbose_name="Publicatiestatus",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Draft"),
                    ("R", "In review"),
                    ("A", "Approved"),
                    ("P", "Published"),
                    ("E", "Expired"),
                    ("X", "Deleted"),
                ],
                max_length=1,
                null=True,
                verbose_name="Publicatiestatus",
            ),
        ),
        migrations.RunPython(set_publication_dates, migrations.RunPython.noop),
    ]
