# Generated by Django 5.2.13 on 2026-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0020_datacontract_publication_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacontract",
            name="last_editor",
            field=models.CharField(
                blank=True,
                default="import",
                help_text="De gebruiker of systeem account die de update doet",
                null=True,
                verbose_name="Last Editor",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="last_editor",
            field=models.CharField(
                blank=True,
                default="import",
                help_text="De gebruiker of systeem account die de update doet",
                null=True,
                verbose_name="Last Editor",
            ),
        ),
    ]
