# Generated by Django 5.2.12 on 2026-04-08 10:00

from django.db import migrations
from django.utils import timezone


def backfill_published_snapshots(apps, schema_editor):
    Product = apps.get_model("beheeromgeving", "Product")
    Team = apps.get_model("beheeromgeving", "Team")
    ProductPublishedSnapshot = apps.get_model("beheeromgeving", "ProductPublishedSnapshot")
    DataContract = apps.get_model("beheeromgeving", "DataContract")
    Distribution = apps.get_model("beheeromgeving", "Distribution")
    DataService = apps.get_model("beheeromgeving", "DataService")

    SNAPSHOT_VERSION = 1

    def _iso(v):
        if v is None:
            return None
        return v.isoformat()

    def _schema_url_for_contract(*, product_schema_url, scopes, tables):
        if not product_schema_url:
            return None
        if scopes and tables:
            return f"{product_schema_url}?scopes={','.join(scopes)}&tables={','.join(tables)}"
        if scopes:
            return f"{product_schema_url}?scopes={','.join(scopes)}"
        return None

    for p in Product.objects.filter(publication_status="P").iterator():
        team = Team.objects.filter(pk=p.team_id).only("po_name", "contact_email").first()
        owner = p._owner or (team.po_name if team else None)
        contact_email = p._contact_email or (team.contact_email if team else None)
        contracts_qs = DataContract.objects.filter(product_id=p.pk).order_by("id")
        services_qs = DataService.objects.filter(product_id=p.pk).order_by("id")
        sources = list(p.sources.values_list("pk", flat=True))
        sinks = list(p.sinks.values_list("pk", flat=True))

        services = [
            {
                "id": s.pk,
                "type": s.type,
                "endpoint_url": s.endpoint_url,
            }
            for s in services_qs
        ]

        contracts = []
        for c in contracts_qs:
            distros_qs = Distribution.objects.filter(contract_id=c.pk).order_by("id")
            distros = [
                {
                    "id": d.pk,
                    "access_service_id": d.access_service_id,
                    "access_url": d.access_url,
                    "download_url": d.download_url,
                    "format": d.format,
                    "filename": d.filename,
                    "type": d.type,
                    "refresh_period": None,
                    "crs": list(d.crs) if d.crs else None,
                }
                for d in distros_qs
            ]

            scopes = list(c.scopes) if c.scopes else None
            tables = list(c.tables) if c.tables else None
            contracts.append(
                {
                    "id": c.pk,
                    "publication_status": c.publication_status,
                    "purpose": c.purpose,
                    "name": c.name,
                    "description": c.description,
                    "last_updated": _iso(c.last_updated),
                    "privacy_level": c.privacy_level,
                    "scopes": scopes,
                    "confidentiality": c.confidentiality,
                    "start_date": _iso(c.start_date),
                    "retainment_period": c.retainment_period,
                    "distributions": distros,
                    "tables": tables,
                    "schema_url": _schema_url_for_contract(
                        product_schema_url=p.schema_url, scopes=scopes, tables=tables
                    ),
                }
            )

        ProductPublishedSnapshot.objects.update_or_create(
            product_id=p.pk,
            defaults={
                "snapshot": {
                    "_snapshot_version": SNAPSHOT_VERSION,
                    "id": p.pk,
                    "name": p.name,
                    "description": p.description,
                    "language": p.language,
                    "is_geo": p.is_geo,
                    "crs": p.crs,
                    "schema_url": p.schema_url,
                    "type": p.type,
                    "contracts": contracts,
                    "themes": list(p.themes) if p.themes else None,
                    "last_updated": _iso(p.last_updated),
                    "created_at": _iso(p.created_at),
                    "refresh_period": p.refresh_period if p.refresh_period else None,
                    "publication_status": p.publication_status,
                    "owner": owner,
                    "contact_email": contact_email,
                    "data_steward": p.data_steward,
                    "services": services,
                    "sources": sources,
                    "sinks": sinks,
                    "team_id": p.team_id,
                },
                "published_at": timezone.now(),
            },
        )


def reverse_backfill(apps, schema_editor):
    ProductPublishedSnapshot = apps.get_model("beheeromgeving", "ProductPublishedSnapshot")
    ProductPublishedSnapshot.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0020_productpublishedsnapshot"),
    ]

    operations = [
        migrations.RunPython(backfill_published_snapshots, reverse_backfill),
    ]
