# Generated by Django 5.2.13 on 2026-04-28 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0021_datacontract_last_editor_product_last_editor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacontract",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="crs",
        ),
    ]
