# Generated by Django 5.2.13 on 2026-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0022_remove_datacontract_description_remove_product_crs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacontract",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Draft"),
                    ("R", "In review"),
                    ("A", "Approved"),
                    ("I", "Internally published"),
                    ("P", "Published"),
                    ("E", "Expired"),
                    ("X", "Deleted"),
                ],
                max_length=1,
                null=True,
                verbose_name="Publicatiestatus",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Draft"),
                    ("R", "In review"),
                    ("A", "Approved"),
                    ("I", "Internally published"),
                    ("P", "Published"),
                    ("E", "Expired"),
                    ("X", "Deleted"),
                ],
                max_length=1,
                null=True,
                verbose_name="Publicatiestatus",
            ),
        ),
    ]
