# Generated by Django 5.2.13 on 2026-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0023_alter_datacontract_publication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="endorsement",
            field=models.CharField(
                blank=True,
                choices=[("C", "Certified"), ("P", "Promoted")],
                help_text="Het endorsement niveau van het Informatieproduct.",
                max_length=1,
                null=True,
                verbose_name="Endorsement niveau",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="other_identifier",
            field=models.CharField(
                blank=True,
                help_text="Een alternatieve identifier voor het Product",
                max_length=128,
                null=True,
                verbose_name="Overige identifier",
            ),
        ),
    ]
