# Generated by Django 5.2.13 on 2026-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0024_product_endorsement_product_other_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Dashboard"),
                    ("M", "Folder"),
                    ("F", "File"),
                    ("C", "Custom"),
                    ("A", "Api"),
                    ("R", "Report"),
                ],
                null=True,
            ),
        ),
    ]
