# Generated by Django 5.2.14 on 2026-06-04 16:00

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0025_alter_distribution_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWorkingCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "other_identifier",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("NL", "Nederlands"), ("EN", "English")],
                        null=True,
                    ),
                ),
                ("is_geo", models.BooleanField(blank=True, null=True)),
                ("schema_url", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("D", "Dataproduct"), ("I", "Informatieproduct")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "themes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("B", "Bestuur"),
                                ("CR", "Cultuur en recreatie"),
                                ("E", "Economie"),
                                ("F", "Financien"),
                                ("H", "Huisvesting"),
                                ("I", "Internationaal"),
                                ("L", "Landbouw"),
                                ("MI", "Migratie en integratie"),
                                ("NM", "Natuur en milieu"),
                                ("OW", "Onderwijs en wetenschap"),
                                ("OOV", "Openbare orde en veiligheid"),
                                ("R", "Recht"),
                                ("RI", "Ruimte en infrastructuur"),
                                ("SZ", "Sociale zekerheid"),
                                ("V", "Verkeer"),
                                ("W", "Werk"),
                                ("ZG", "Zorg en gezondheid"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("_owner", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "data_steward",
                    models.CharField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "_contact_email",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("refresh_period", models.JSONField(default=dict, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "last_editor",
                    models.CharField(blank=True, default="import", max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("base_last_updated", models.DateTimeField()),
                (
                    "endorsement",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Certified"), ("P", "Promoted")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_copy",
                        to="beheeromgeving.product",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_working_copies",
                        to="beheeromgeving.team",
                    ),
                ),
            ],
        ),
    ]
