# Generated by Django 5.2.14 on 2026-06-04 14:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0026_productworkingcopy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataContractWorkingCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("purpose", models.TextField(blank=True, null=True)),
                (
                    "privacy_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NPI", "Niet persoonlijk identificeerbaar"),
                            ("PI", "Persoonlijk identificeerbaar"),
                            ("BI", "Bijzonder identificeerbaar"),
                        ],
                        null=True,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "last_editor",
                    models.CharField(blank=True, default="import", max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confidentiality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O", "Openbaar"),
                            ("I", "Intern"),
                            ("V", "Vertrouwelijk"),
                            ("G", "Geheim"),
                        ],
                        null=True,
                    ),
                ),
                ("retainment_period", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "tables",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("base_last_updated", models.DateTimeField()),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_copy",
                        to="beheeromgeving.datacontract",
                    ),
                ),
            ],
        ),
    ]
