# Generated by Django 5.2.14 on 2026-06-04 16:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0027_datacontractworkingcopy"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacontractworkingcopy",
            name="has_distribution_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DataContractWorkingCopyDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_service_id", models.IntegerField(blank=True, null=True)),
                (
                    "access_url",
                    models.URLField(
                        blank=True,
                        help_text="Toegangslink naar de distributie.",
                        null=True,
                        verbose_name="Access URL",
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True,
                        help_text="Link naar het bestand dat opgeslagen is binnen de omgeving van het Datateam op het Dataplatform",
                        null=True,
                        verbose_name="Download URL",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        help_text="Het bestandsformaat: CSV, CAD, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="Bestandstype",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="De naam van het bestand.",
                        max_length=255,
                        null=True,
                        verbose_name="Bestandsnaam",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "Dashboard"),
                            ("M", "Folder"),
                            ("F", "File"),
                            ("C", "Custom"),
                            ("A", "Api"),
                            ("R", "Report"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "refresh_period",
                    models.CharField(
                        blank=True,
                        help_text="Om de hoeveel tijd de data in het Data Product ververst wordt",
                        max_length=64,
                        null=True,
                        verbose_name="Ververstermijn",
                    ),
                ),
                (
                    "crs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("RD", "RD"),
                                ("ETRS89", "ETRS89"),
                                ("WGS84", "WGS84"),
                                ("UTM35S", "UTM35S"),
                            ],
                            max_length=9,
                            verbose_name="Geo coördinaatreferentiesysteem",
                        ),
                        blank=True,
                        help_text="Geo-informatie is direct gekoppeld aan een locatie op aarde. De manier waarop die koppeling wordt gelegd, wordt beschreven in het coördinaatreferentiesysteem (CRS). Hierin worden coördinaten van een locatie vastgelegd. Een distributie kan meerdere CRS'en ondersteunen.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "live_distribution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_copy",
                        to="beheeromgeving.distribution",
                    ),
                ),
                (
                    "working_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="beheeromgeving.datacontractworkingcopy",
                    ),
                ),
            ],
        ),
    ]
