# Generated by Django 5.2.14 on 2026-09-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beheeromgeving", "0032_remove_distribution_service_coupling"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrevision",
            name="has_service_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProductRevisionService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REST", "Rest"),
                            ("WMS", "Wms"),
                            ("WMTS", "Wmts"),
                            ("WFS", "Wfs"),
                            ("MVT", "Mvt"),
                            ("ATOM", "Atom"),
                        ],
                        help_text="Soort API: REST, atom, etc.",
                        max_length=10,
                        null=True,
                        verbose_name="API Type",
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(blank=True, null=True, verbose_name="API Link (Intern)"),
                ),
                (
                    "live_service",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revision_copy",
                        to="beheeromgeving.dataservice",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_services",
                        to="beheeromgeving.productrevision",
                    ),
                ),
            ],
        ),
    ]
